title: "灯火烛天|Lus"
author: "灯火烛天"
description: "Written by 灯火烛天"
permalink: /:title/
lang: "zh"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "README.md"}
  - {url: "https://lightupsky.xyz/Announcement.html", title: "公告"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:lightupsky123@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Lightupsky"}
  - {title: Bili, icon: youtube, url: "https://space.bilibili.com/27694266"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
